// <auto-generated />
namespace Moemisto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Event_ShortInfoSetLen900 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_ShortInfoSetLen900));
        
        string IMigrationMetadata.Id
        {
            get { return "201507221913143_Event_ShortInfoSetLen900"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
